
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Frame1 extends javax.swing.JFrame {
    String temp = "";
    Double ti, bt, h1;
    
    
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        btnCobalagi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Diagnosa2 = new javax.swing.JTextField();
        Diagnosa1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nama");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 35, 17);

        jLabel2.setFont(new java.awt.Font("absender", 0, 36)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 10, 290, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 120, 36, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Berat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 160, 32, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 200, 79, 17);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(190, 80, 193, 30);

        Tinggi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Tinggi);
        Tinggi.setBounds(190, 120, 85, 30);

        Berat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Berat);
        Berat.setBounds(190, 160, 85, 30);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(190, 200, 110, 25);

        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbLaki.setText("Laki-laki");
        getContentPane().add(rbLaki);
        rbLaki.setBounds(310, 200, 71, 25);

        btnCobalagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCobalagi.setText("Cobalagi");
        btnCobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCobalagi);
        btnCobalagi.setBounds(240, 240, 110, 40);

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(120, 290, 230, 40);

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung);
        btnHitung.setBounds(120, 240, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 400, 170, 17);

        Ideal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Ideal);
        Ideal.setBounds(230, 350, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 120, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 350, 20, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 160, 30, 30);

        Diagnosa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Diagnosa2);
        Diagnosa2.setBounds(20, 470, 430, 30);

        Diagnosa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Diagnosa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnosa1ActionPerformed(evt);
            }
        });
        getContentPane().add(Diagnosa1);
        Diagnosa1.setBounds(20, 430, 430, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 350, 200, 17);

        setBounds(0, 0, 493, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void Diagnosa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnosa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diagnosa1ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        if(Nama.getText().equals("")||Tinggi.getText().equals("")||
                Berat.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Data harus diisi");
        }
        
        else if(rbPerempuan.isSelected()||rbLaki.isSelected()){
            try {
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data harus diisi");
            }
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobalagiActionPerformed
        Nama.setText("");
        buttonGroup1.clearSelection();
        Berat.setText("");
        Tinggi.setText("");
        Ideal.setText("");
        Diagnosa1.setText("");
        Diagnosa2.setText("");
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobalagiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Diagnosa1;
    private javax.swing.JTextField Diagnosa2;
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnCobalagi;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(Tinggi.getText());
        bt = Double.valueOf(Berat.getText());
        
        if(rbLaki.isSelected()){
            h1 = (ti-100) * 1;
        }
        
        else if(rbPerempuan.isSelected()){
            h1 = (ti-104) * 1;
        }
        
        temp = Double.toString(h1.intValue());
        
        if(h1 < bt) {
            Ideal.setText(temp);
            Diagnosa1.setText("Maaf " + Nama.getText() + ", sepertinya Anda OVERWEIGHT :( " );
            Diagnosa2.setText("Banyaklah berolahraga dan hindari makanan berkolestrol"); 
        }
        
        else if(h1 > bt){
            Ideal.setText(temp);
            Diagnosa1.setText("Maaf " + Nama.getText() + ", sepertinya Anda UNDERWEIGHT :( " );
            Diagnosa2.setText("Banyaklah mengkonsumsi makanan berkarbohidrat"); 
        }
        
        else {
            Ideal.setText(temp);
            Diagnosa1.setText("Hello " + Nama.getText() + ", berat badan anda sudah ideal :) " );
            Diagnosa2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat"); 
        }
        
        //To change body of generated methods, choose Tools | Templates.
    }
}
